#!/bin/bash

BATTINFO=`acpi -b`

if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 5 -d " "` < 00:15:00 ]] ; then
  DISPLAY=:0.0 /usr/bin/notify-send "Oops ! Zorx check the battery" `echo $BATTINFO | cut -f 2 -d ","`
fi
