#!/bin/bash
# Bash script to control the monitor brightness
current_brightness=$(xrandr --verbose | grep -i brightness | awk '{print $2}')
max_brightness=1.0
min_brightness=0.5

if [ "$1" == "+" ]; then
    new_brightness=$(echo "$current_brightness + 0.1" | bc)
    if (( $(echo "$new_brightness > $max_brightness" | bc -l) )); then
        new_brightness=$max_brightness
    fi
elif [ "$1" == "-" ]; then
    new_brightness=$(echo "$current_brightness - 0.1" | bc)
    if (( $(echo "$new_brightness < $min_brightness" | bc -l) )); then
        new_brightness=$min_brightness
    fi
else
    echo "Usage: $0 [+ | -]"
    exit 1
fi

screenname=$(xrandr | grep " connected" | cut -f1 -d" ")
xrandr --output $screenname --brightness $new_brightness
